modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="work_platform"
version="1.0.1"
displayName="Work platform"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="508364"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.work_platform]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.work_platform]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration